CREATE SCHEMA "ROOT";

SET SCHEMA "ROOT";

CREATE TABLE IDENTITIES
    (
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
	CONSTRAINT IDENTITY_PK PRIMARY KEY, 
    DISPLAY_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    UID VARCHAR(255)
	);
	
CREATE TABLE LOGIN_USERS
	(
	ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    USERNAME VARCHAR(255),
    HASHED_PASSWORD VARCHAR(255),
    IDENTITYID INT REFERENCES IDENTITIES(ID) ON DELETE CASCADE
	);
	
INSERT INTO IDENTITIES (DISPLAY_NAME, EMAIL, UID)
	VALUES ('root','null','1');
INSERT INTO LOGIN_USERS (USERNAME, HASHED_PASSWORD, IDENTITYID)
	VALUES('root','63a9f0ea7bb98050796b649e85481845',1);