INSERT INTO IDENTITIES(DISPLAY_NAME,EMAIL,UID) VALUES ('SAMER','SAMER@SAMER.COM','123');

INSERT INTO LOGIN_USERS(USERNAME,HASHED_PASSWORD,IDENTITYID) VALUES ('SAMER_MASSAD','TESTPASS',1);

SELECT I.*, L.*
FROM IDENTITIES I
	INNER JOIN LOGIN_USERS L ON L.IDENTITYID = I.ID;
	
SELECT L.USERNAME, L.HASHED_PASSWORD, L.IDENTITYID
FROM IDENTITIES I
	INNER JOIN LOGIN_USERS L ON L.IDENTITYID = I.ID
WHERE (I.UID = '2') AND (L.USERNAME LIKE '%g%');

UPDATE LOGIN_USERS SET USERNAME='Samer Massad', HASHED_PASSWORD='Test'
WHERE IDENTITYID=(SELECT ID FROM IDENTITIES WHERE UID='2');

SET SCHEMA "ROOT";
SELECT L.USERNAME, L.HASHED_PASSWORD, I.UID
FROM IDENTITIES I
INNER JOIN LOGIN_USERS L ON L.IDENTITYID = I.ID
WHERE (I.UID = '25') ;

SELECT L.USERNAME, L.HASHED_PASSWORD, I.UID
FROM IDENTITIES I
INNER JOIN LOGIN_USERS L ON L.IDENTITYID = I.ID
WHERE (0 = 1 OR I.UID = '1');